FROM node:22.14-alpine

# set working directory
WORKDIR /app

# Add build dependencies
RUN apk add --no-cache python3 make g++ git

# install and cache app dependencies
COPY package*.json /app/

RUN npm install --legacy-peer-deps

COPY . /app/

# start app
CMD [ "npm", "run", "serve" ]