FROM node:22.14-alpine

WORKDIR /app

# Add build dependencies
RUN apk add --no-cache python3 make g++ git

COPY package*.json /app/

RUN npm install --legacy-peer-deps

COPY . /app/

CMD [ "npm", "run", "devstart" ]